name: Anna Bureta
title: FancyZones User Guide
description: A guide on how to set up FancyZones, a window manager for Windows users
remote_theme: KomunikacjaTechnicznaVistula/just-the-docs

color_scheme: ab.scss

aux_links:
  "Source repository on GitHub":
    - "//github.com/KomunikacjaTechnicznaVistula/Anna-Bureta"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: This document was created as part of my technical writing training at Vistula University.